### PR TITLE
Readme file

### PR DESCRIPTION
**Pull request by IMPrimph**

### CODE REVIEW

**Review by ksheetal — CHANGES_REQUESTED** [review]
Hi @IMPrimph 
where did you find these images?
it might contain copyright issue. 
please use only Skill-Class repo. you can take a screenshot and create a pull req.

Thanks

**Comment by IMPrimph** [comment]
@ksheetal 
Ok, iI will update

**Comment by IMPrimph** [comment]
@ksheetal 
A small doubt, after I have sent the pull request, hactoberfest website is saying that the PR was submitted to an ineligible repo

**Comment by ksheetal** [comment]
> @ksheetal
> A small doubt, after I have sent the pull request, hactoberfest website is saying that the PR was submitted to an ineligible repo

Its because I did not add the hactoberfest label. I have added that now. Also, the digital ocean is only allowing meaningful contributions so even if you are updating the readme make sure you do it in the right way.

**Comment by IMPrimph** [comment]
@ksheetal 
I have updated with my screenshots from the skill-class repository, so there won't be any copyright issue for you.
And further, yesterday, there was some problem with the pull requests, now I have forked again and made a new pull request.
Thank you

**Comment by ksheetal** [comment]
> @ksheetal
> I have updated with my screenshots from the skill-class repository, so there won't be any copyright issue for you.
> And further, yesterday, there was some problem with the pull requests, now I have forked again and made a new pull request.
> Thank you

Yeah. good job.

**Pull request closed without merging**
